#pragma once

enum MAINTAINID { MAINTAIN_STATIC, MAINTAIN_LOADING, MAINTAIN_STAGE, MAINTAIN_END };
enum LAYERID { LAYER_ENVIRONMEMT, LAYER_GAMELOGIC, LAYER_CAMERA, LAYER_UI };
enum OBJECT_TAG { TAG_PLAYER, TAG_TEAM_AI, TAG_ENEMY, TAG_CAMERA, TAG_MAPOBJECT, TAG_END };